# Generated by Django 4.1.1 on 2022-09-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name="User's ID")),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created account')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated account')),
            ],
        ),
    ]
